name: Secrets Deploy
author: gitgregoryjones 
description: Build,Push a docker image to Amazon ECR (create if not found), Create Task Definition, Push ENV variables from ASM and restart ECS service
inputs:
  AWS_ACCESS_KEY_ID:
    description: Access key for IAM User.
  AWS_SECRET_ACCESS_KEY:
    description: Secret access key for IAM User.
  project_name:
    description: The name of this project will be used as ECR repository created/updated
    required: false
  stage:
    description: Will be used to read secrets from {project-name}-{stage} Secrets Manager path [development,staging,production,etc] and pushed to container ENV
    required: true
  region:
    description: AWS Region to use.  Defaults to us-east-2.
    required: false
  global_region:
    description: (default us-east-1) AWS Region used for services we want to treat as global.  Currently Secrets Manager
    required: false 
  slack_hook_url:
    description: Notifications will be sent to this Slack Hook if provided
    required: false
  CREDENTIALS_JSON: 
    description: JSON object of AWS credentials for each ENV {"production":{AWS_ACCESS_KEY_ID:"1234X","AWS_SECRET_ACCESS_KEY":"19292929"},"development":{"AWS_ACCESS_KEY_ID":"102939383","AWS_SECRET_ACCESS_KEY":"92299292"}}
    required: false
runs:
  using: node12
  main: 'main.js'
branding:
  icon: upload
  color: orange
